version: 2.1

jobs:
  first-job:
    docker:
      - image: cimg/ruby:2.7-node

    steps:
      - checkout
      - run: echo "Hello CircleCI!"

workflows:
  build:
    jobs:
    - first-job
    
    
    
